<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>SublimeText2 Syntax Definition for Behat - EN</string>
	<key>fileTypes</key>
	<array>
		<string>feature</string>
	</array>
	<key>name</key>
	<string>Behat Features - English</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.feature.generic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat definitions</string>
			<key>match</key>
			<string>(Feature:|Examples:|Scenario:|Scenario Outline:|Background:)</string>
			<key>name</key>
			<string>keyword.control.source.behat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat step keyword</string>
			<key>match</key>
			<string>(Given |When |And |But |Then )</string>
			<key>name</key>
			<string>keyword.operator.step.behat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.feature.english</string>
	<key>uuid</key>
	<string>14cc7372-dcbe-47f1-8c96-325d423c3363</string>
</dict>
</plist>
