<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>SublimeText2 Syntax Definition for Behat - IT</string>
	<key>fileTypes</key>
	<array>
		<string>feature</string>
	</array>
	<key>name</key>
	<string>Behat Features - Italian</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.feature.generic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat definitions</string>
			<key>match</key>
			<string>(Funzionalità:|Esempi:|Scenario:|Schema dello scenario:|Contesto:)</string>
			<key>name</key>
			<string>keyword.control.source.behat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat step keyword</string>
			<key>match</key>
			<string>(Dato |Data |Dati |Date |Quando |Allora |E |Ma )</string>
			<key>name</key>
			<string>keyword.operator.step.behat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.feature.italian</string>
	<key>uuid</key>
	<string>be973dfd-6f92-480e-9034-bd1f6570bc8e</string>
</dict>
</plist>
