<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>SublimeText2 Syntax Definition for Behat - DE</string>
	<key>fileTypes</key>
	<array>
		<string>feature</string>
	</array>
	<key>name</key>
	<string>Behat Features - German</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.feature.generic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat definitions</string>
			<key>match</key>
			<string>(Funktionalität:|Beispiele:|Szenario:|Szenariogrundriss:|Grundlage:)</string>
			<key>name</key>
			<string>keyword.control.source.behat</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Behat step keyword</string>
			<key>match</key>
			<string>(Angenommen |Gegeben sei |Wenn |Dann |Und |Aber )</string>
			<key>name</key>
			<string>keyword.operator.step.behat</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.feature.german</string>
	<key>uuid</key>
	<string>ae32f8ed-c632-4cc3-8a4b-a69234dcefaa</string>
</dict>
</plist>
