<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>comment</key>
  <string>SublimeText2 Syntax Definition for Behat</string>
  <key>fileTypes</key>
  <array>
    <string>feature</string>
  </array>
  <key>name</key>
  <string>Behat Features</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>Behat scenario tags</string>
      <key>match</key>
      <string>(@[A-Za-z0-9_]+)</string>
      <key>name</key>
      <string>storage.type.class.behat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>#</string>
      <key>comment</key>
      <string>Behat comment</string>
      <key>end</key>
      <string>\n</string>
      <key>name</key>
      <string>comment.line.number-sign.behat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>comment</key>
      <string>Behat strings</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.double.behat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>&lt;</string>
      <key>comment</key>
      <string>Behat placeholders</string>
      <key>end</key>
      <string>&gt;</string>
      <key>name</key>
      <string>string.interpolated.behat</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>^\s*\|</string>
      <key>comment</key>
      <string>Behat outline examples</string>
      <key>end</key>
      <string>\|\s*$</string>
      <key>name</key>
      <string>string.quoted.examples.behat</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\w+</string>
          <key>name</key>
          <string>constant.other.examples.behat</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: EN</string>
      <key>match</key>
      <string>^\s*((?:Feature|Business Need|Ability|Examples|Scenario|Scenarios|Scenario Outline|Scenario Template|Background):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: EN</string>
      <key>match</key>
      <string>^\s*(Given|When|And|But|Then)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: FR</string>
      <key>match</key>
      <string>^\s*((?:Fonctionnalité|Exemples|Scénario|Plan du scénario|Plan du Scénario|Contexte):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: FR</string>
      <key>match</key>
      <string>^\s*(Lorsqu(?:'|’)|Soit|Etant donné|Etant donnée|Etant donnés|Etant données|Étant donné|Étant donnée|Étant donnés|Étant données|Quand|Lorsque|Alors|Et|Mais)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: IT</string>
      <key>match</key>
      <string>^\s*((?:Funzionalità|Esempi|Scenario|Schema dello scenario|Contesto):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: IT</string>
      <key>match</key>
      <string>^\s*(Dato|Data|Dati|Date|Quando|Allora|E|Ma)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: ES</string>
      <key>match</key>
      <string>^\s*((?:Característica|Ejemplos|Escenario|Esquema del escenario|Antecedentes):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: ES</string>
      <key>match</key>
      <string>^\s*(Dado|Dada|Dados|Dadas|Cuando|Entonces|Y|Pero)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: PT</string>
      <key>match</key>
      <string>^\s*((?:Funcionalidade|Característica|Caracteristica|Exemplos|Cenário|Cenario|Esquema do Cenário|Esquema do Cenario|Delineação do Cenário|Delineacao do Cenario|Contexto|Cenário de Fundo|Cenario de Fundo|Fundo):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: PT</string>
      <key>match</key>
      <string>^\s*(Dado|Dada|Dados|Dadas|Quando|Então|Entao|E|Mas)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: DE</string>
      <key>match</key>
      <string>^\s*((?:Funktionalität|Beispiele|Szenario|Szenariogrundriss|Grundlage):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: DE</string>
      <key>match</key>
      <string>^\s*(Angenommen|Gegeben sei|Wenn|Dann|Und|Aber)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Source" translations: RU</string>
      <key>match</key>
      <string>^\s*((?:Функция|Функционал|Свойство|Примеры|Сценарий|Структура сценария|Предыстория|Контекст):)</string>
      <key>name</key>
      <string>keyword.control.source.behat</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>"Steps" translations: RU</string>
      <key>match</key>
      <string>^\s*(Допустим|Пусть|Дано|К тому же|Также|И|Когда|Если|Тогда|То|Но|А)\b</string>
      <key>name</key>
      <string>keyword.operator.step.behat</string>
    </dict>   
  </array>
  <key>scopeName</key>
  <string>source.feature.generic</string>
  <key>uuid</key>
  <string>45340a49-8e17-474d-9ab0-0c17e6ca5be0</string>
</dict>
</plist>
